;; Bootstrap
;; This file is generated by init.el at compile time.

(load-file "~/.emacs.d/global-settings/archives-trivialfis.el")
(setq package-selected-package
      'nil)
(package-install-selected-packages)

(load-file "~/.emacs.d/init.el")

;; Local Variables:
;; flycheck-disabled-checkers: (emacs-lisp-checkdoc emacs-lisp)
;; End:
